### PR TITLE
Add support for open extensions

### PR DESCRIPTION
**Pull request by christophwille**
This is a work in progress with request for review.

It implements the open extensions workflow shown in the documentation (https://developer.microsoft.com/en-us/graph/docs/concepts/extensibility_open_users). Notable at this stage:

 * Not using resources (like UserController does)
 * One (possible) bug in the client sdk (see line 55 in ExtensionsService.cs) - I have not tried with the latest Graph client sdk; how should I work around this behavior?

### CODE REVIEW

**Comment by jamescro** [comment]
Thanks so much for the contribution and for checking in. I'll take a closer look later today or tomorrow. We've settled on using resources  for strings as a best practice. Would you object to using them here?

I'll check with the SDK engineers about the null result you're getting on line 55. Sometimes this reflects behavior in the service, but it could be a bug. Could you have that method return a Boolean for success (no exception) as a workaround?

**Comment by christophwille** [comment]
Resources: I am perfectly fine with those, just didn't want to put them there until the scenario I built is ok'ed.

UpdateAsync: I can work around that, it's just that the SDK behavior / method signature is strange. Because according to (REST API) documentation, the result should be 204 with no content at all. So UpdateAsync should actually have a return of void instead of Extension.

**Comment by jamescro** [comment]
I followed up with one of our SDK developers. He pointed out that our SDKs are generated by a build that works from a template. Some of the update operations do return the updated items, and some do not. The template has to account for both scenarios, so occasionally the signature will indicate that an item will be returned when, in fact, the underlying service doesn't return anything.

**Comment by jamescro** [comment]
I've also looked more closely at your code, and this looks great. Thanks so much for doing this work. When you have your strings in resources, I'll run through it end-to-end.

**Comment by christophwille** [comment]
I have amended my pull request as per the requests here. I kept a comment regarding the return value of UpdateAsync.

**Comment by jamescro** [comment]
Just merged your PR. Thanks so much for doing this work!

**Comment by christophwille** [comment]
If I have time I'll look into schemaExtensions. But that needs app permissions.

**Pull request merged**
